### ISSUE TITLE
Including DATA  (changes needed to Pavel's recent repository)

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/climatology_pi#15]
In Pavel's Repository, recently, there were changes so Data was not included. These are the changes I made to include the data before compiling.  He may have fixed this but it is not in his repos now.

Include DATA with Climatology.

Climatology Data location
----------------------------------
Put the data in a {PROJECT_SOURCE_DIR}/data directory
Add the data into  "climatology_pi/data"

Changes in Pavel's repository version of  cmake/pluginstall.cmake to read
------------------------
Start at Line 78
 IF(${BUNDLE_DATA} AND EXISTS ${PROJECT_SOURCE_DIR}/data)
    INSTALL(DIRECTORY data DESTINATION "${INSTALL_DIRECTORY}")
  ENDIF(${BUNDLE_DATA} AND EXISTS ${PROJECT_SOURCE_DIR}/data)
ENDIF(WIN32)

Start at Line 88
IF(${BUNDLE_DATA} AND EXISTS ${PROJECT_SOURCE_DIR}/data)
    INSTALL(DIRECTORY data DESTINATION ${PREFIX_PARENTDATA}/plugins/${PACKAGE_NAME})
  ENDIF(${BUNDLE_DATA} AND EXISTS ${PROJECT_SOURCE_DIR}/data)
ENDIF(UNIX AND NOT APPLE)

CmakeLists.txt file  settings
---------------------------------------
SET(BUNDLE_DATA TRUE)

(I suppose the BUNDLE_DATA could be removed if we are always including data.).

**Comment by nohal** [comment]
Rick...
Can you explain what are we talking about here to a total noob like me, please?
Have you tried to install http://sourceforge.net/projects/opencpnplugins/files/climatology_pi/climatology_pi-1.1-win32.exe/download which is made from my packaging repository? Does that 6.2MB file not contain data for you? Is the data not found? Is it installed into a wrong location on your system?
I also highly doubt you are talking about my repository, as you can see at https://github.com/nohal/climatology_pi/blob/master/cmake/PluginInstall.cmake#L88 or maybe you are, but about the half a year old pack branch, not the current code...

Please make sure to look at the right code before starting to fix it...

Thanks

Pavel

**Comment by rgleason** [comment]
Pavel, you are no noob. I tried git fetch from your repos and compiled, no data. So then I tried Seans repos and it added data.  So then tried to fix my clone of your repos and succeeded. Maybe I will remove the clone and re-clone your repos and try it again.  

Sorry, about the confusion.

**Comment by nohal** [comment]
Rick...
Sorry to repeat that, but I would be much more grateful for testing of the plugins officially published at http://opencpn.org/ocpn/opencpn41_plugins and filling bugs for the functional issues.

Pavel

**Comment by rgleason** [comment]
Yes. I've updared and will be testing most all that I have equipment for and report on tracker.

Thank you Pavel for being patient with me.
