### ISSUE TITLE
problem compiling climatology 1.2

### ISSUE THREAD

**Issue by filochard** [seandepagnier/climatology_pi#16]
Hi 
I found a problem trying to compile the last version of Climatology_pi (version 1.2 2015 december 9th)
I get this error

BUILD/climatology_pi/src/ClimatologyDialog.cpp:57:19: fatal error: now.xpm: No such file or directory
 #include "now.xpm"
did you forget to add this file in the climatology_pi/src/ directory

**Comment by rgleason** [comment]
I believe it does compile. Keep in mind it does need the data!
Refer to readme also.

**Comment by rgleason** [comment]
Can you please close this?

**Comment by rgleason** [comment]
I can't

**Comment by rgleason** [comment]
I have tested climatolgy again, current version.  It compiles fine.  
Sean perhaps you can close this. I can't close it. Thanks.


> Build succeeded.
>     0 Warning(s)
>     0 Error(s)
> 
> Time Elapsed 00:00:01.93
> 
> C:\Users\Rick\Documents\GitHub\o-plugin\s-climatology_pi\build>cpack
> CPack: Create package using NSIS
> CPack: Install projects
> CPack: - Install project: climatology_pi
> CPack: Create package
> CPack: - package: C:/Users/Rick/Documents/GitHub/o-plugin/s-climatology_pi/build/climatology_pi-1.2-win32.exe generated.
> 
> C:\Users\Rick\Documents\GitHub\o-plugin\s-climatology_pi\build>git branch -va
> * master                af3b40c Merge branch 'master' of ssh://github.com/seandepagnier/climatology_pi
>   remotes/origin/HEAD   -> origin/master
>   remotes/origin/master af3b40c Merge branch 'master' of ssh://github.com/seandepagnier/climatology_pi
