### ISSUE TITLE
please tag releases

### ISSUE THREAD

**Issue by mschiff** [seandepagnier/climatology_pi#18]
Dear developer,

I would like to make your plugin available to the users of Gentoo Linux.

Right now this is not possible because there are no releases available for your plugin.

It would be very usefull to have tagged releases, so the source for a specific version of the plugin can be downloaded. Please add a release/tag for your released versions. This makes packaging a lot easier.

Please see: [Creating Releases](https://help.github.com/articles/creating-releases/)

Thanks in advance!

**Comment by tchiwam** [comment]
mschiff, In the mean time do you have a working commit for version 4.8 ? I am trying to install this one on a gentoo system too.

**Comment by mschiff** [comment]
@tchiwam you can alyways try the live version, but without defined releases its always luck if you are able to install this plugin at some time or not because it does not build and so on..

On github, its so easy to do releases, so I really do not see, whats the problem with this :-(

**Comment by mschiff** [comment]
@seandepagnier any news on this? are you still maintaining this plugin?

**Comment by rgleason** [comment]
You could try my repository which is for Windows, but perhaps it will help. https://github.com/rgleason/weather_routing_pi

**Comment by seandepagnier** [comment]
@mschiff I am maintining the plugin and just tagged a release for this and several plugins
