### ISSUE TITLE
Will not compile now

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/climatology_pi#36]
"C:\Users\Rick\Documents\GitHub\climatology_pi\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\Rick\Documents\GitHub\climatology_pi\build\climatology_pi.vcxproj" (default target) (5) -
Seandepagnier implement automatic download of climatology data
Latest commit 42c916e 4 days ago    June 8, 2018

>
(ClCompile target) ->
  C:\Users\Rick\Documents\GitHub\climatology_pi\src\ClimatologyOverlayFactory.cpp(205): error C2146
: syntax error : missing ')' before identifier 'wxGetTranslation' [C:\Users\Rick\Documents\GitHub\c
limatology_pi\build\climatology_pi.vcxproj]
  C:\Users\Rick\Documents\GitHub\climatology_pi\src\ClimatologyOverlayFactory.cpp(206): error C2059
: syntax error : ')' [C:\Users\Rick\Documents\GitHub\climatology_pi\build\climatology_pi.vcxproj]

    2 Warning(s)
    2 Error(s)

https://msdn.microsoft.com/en-us/library/9xbcaa9t.aspx
https://stackoverflow.com/questions/2706277/error-c2146-syntax-error-missing-before-identifier-vertices

https://msdn.microsoft.com/en-us/library/t8xe60cf.aspx
https://stackoverflow.com/questions/15734367/error-c2059-syntax-error-when-adding-c-source-files-to-project

**Comment by LeaseOnLife** [comment]
same problem on linux ubuntu 18.04:

climatology_pi/src/ClimatologyOverlayFactory.cpp:205:42: error: expected ‘)’ before ‘wxGetTranslation’
                                          _("Climatology data incomplete"),
                                          ^

**Comment by Nereus32** [comment]
Same on mac. Stops compiling here:

[ 82%] Building CXX object CMakeFiles/climatology_pi.dir/src/ClimatologyOverlayFactory.cpp.o
In file included from /Users/nereus/build-release/climatology_pi/src/ClimatologyOverlayFactory.cpp:34:
/System/Library/Frameworks/OpenGL.framework/Headers/gl3.h:15:2: warning: gl.h
      and gl3.h are both included. Compiler will not invoke errors if using
      removed OpenGL functionality. [-W#warnings]
#warning gl.h and gl3.h are both included.  Compiler will not invoke err...
 ^
/Users/nereus/build-release/climatology_pi/src/ClimatologyOverlayFactory.cpp:205:42: error: 
      expected ')'
                                         _("Climatology data incomplete"),
                                         ^
/usr/local/include/wx-3.1/wx/translation.h:38:48: note: expanded from macro '_'
    #define _(s)                               wxGetTranslation((s))
                                               ^
/Users/nereus/build-release/climatology_pi/src/ClimatologyOverlayFactory.cpp:202:41: note: 
      to match this '('
                    wxMessageDialog mdlg(&m_dlg,
                                        ^
/Users/nereus/build-release/climatology_pi/src/ClimatologyOverlayFactory.cpp:1237:16: warning: 
      absolute value function 'fabsf' given an argument of type 'double' but has
      parameter of type 'float' which may cause truncation of value
      [-Wabsolute-value]
            if(fabsf((double)lat/10) >= 90 || (double)lon/10 > 15 || (do...
               ^
/Users/nereus/build-release/climatology_pi/src/ClimatologyOverlayFactory.cpp:1237:16: note: 
      use function 'std::abs' instead
            if(fabsf((double)lat/10) >= 90 || (double)lon/10 > 15 || (do...
               ^~~~~
               std::abs
/Users/nereus/build-release/climatology_pi/src/ClimatologyOverlayFactory.cpp:1237:16: note: 
      include the header <cmath> or explicitly provide a declaration for
      'std::abs'
In file included from /Users/nereus/build-release/climatology_pi/src/ClimatologyOverlayFactory.cpp:46:
In file included from /Users/nereus/build-release/climatology_pi/src/climatology_pi.h:54:
In file included from /Users/nereus/build-release/climatology_pi/src/ClimatologyDialog.h:39:
/Users/nereus/build-release/climatology_pi/src/ClimatologyOverlayFactory.h:301:9: warning: 
      private field 'm_cyclonesDisplayList' is not used [-Wunused-private-field]
    int m_cyclonesDisplayList;
        ^
3 warnings and 1 error generated.
make[2]: *** [CMakeFiles/climatology_pi.dir/src/ClimatologyOverlayFactory.cpp.o] Error 1
make[1]: *** [CMakeFiles/climatology_pi.dir/all] Error 2
make: *** [all] Error 2

**Comment by LeaseOnLife** [comment]
latest commit fixes the problem, at least on Linux.

**Comment by rgleason** [comment]
Thanks Leaseonlife.  Windows still does not compile. One error.

> "C:\Users\Rick\Documents\GitHub\climatology_pi\build\ALL_BUILD.vcxproj" (default target) (1) ->
> "C:\Users\Rick\Documents\GitHub\climatology_pi\build\climatology_pi.vcxproj" (default target) (5) -
> >
> (Link target) ->
>   LINK : fatal error LNK1181: cannot open input file 'Release\LIB_PLUGINXML.lib' [C:\Users\Rick\Doc
> uments\GitHub\climatology_pi\build\climatology_pi.vcxproj]
> 
>     2 Warning(s)
>     1 Error(s)
> 

The pluginxml.cmake file has this now

> IF(WIN32)
> SET(SRC_TINYXML
>             src/tinyxml/tinyxml.cpp
>             src/tinyxml/tinyxmlparser.cpp
>             src/tinyxml/tinyxmlerror.cpp
> )
> ADD_LIBRARY(LIB_PLUGINXML STATIC ${SRC_TINYXML})
> TARGET_LINK_LIBRARIES( ${PACKAGE_NAME} LIB_PLUGINXML )
> ENDIF(WIN32)
> 
> ADD_DEFINITIONS(-DTIXML_USE_STL)
> 

And cmakecache.txt  has this line

> //Dependencies for target
> LIB_PLUGINXML_LIB_DEPENDS:STATIC=

**Comment by rgleason** [comment]
Sean can this be fixed?  We do have a working version, but it would be nice to have it up to date before the reasons for the problem are forgotten.

**Comment by LeaseOnLife** [comment]
I am just getting my feet wet in windows-compilations. it fails as described by Rick above. To me it looks like, for Windows, Sean needs to add his choice of tinyxml into src, as he has done for bzip, wxJSON, zlib...

**Comment by rgleason** [comment]
Compliles now

**Comment by pa2wlt** [comment]
@rgleason @seandepagnier the manual uses climatologi_pi as an example on how to compile plugins for Windows. I followed the steps, updated the manual where necessary, though climatology_pi does not build. I can't find Zlib. Zlib that isn't installed by default on a new Windows 10 installation. Downloading and building Zlib is not the issue, though the CMakeLists.txt for climatology_pi requires the files to be in rather specfic directories, with particular names. I reckon this dependency should be be added in the README, including some comments on how to make Zlib and where to save it. Otherwise climatology_pi won't build on Windows.

**Comment by rgleason** [comment]
Of course it builds, it had to be built for Ov5.0.0.
Please see https://ci.appveyor.com/project/rgleason/climatology-pi/builds/24824700
and 
https://ci.appveyor.com/project/rgleason/climatology-pi/builds/24824700/artifacts
or click on the Release Tab from [this Page](https://github.com/rgleason/climatology_pi)

Perhaps try cloning my repository?  I am not sure where Sean's is right now.

**Comment by pa2wlt** [comment]
Thx @rgleason. The only thing I can see there, is it was built 6 month ago. The thing I'm telling you, is it doesnot build currently, while following exactly the steps in the manual. The manual refers to [git clone https://github.com/seandepagnier/climatology_pi](git clone https://github.com/seandepagnier/climatology_pi)

I will give it one more try while checking out you library. If it still doesn't work, I will update the manual using watchdog_pi, since that one builds immediately with the same steps.

**Comment by rgleason** [comment]
Werner, 
Note that appveyor.yml builds and deploys successfully.
I have looked into this and have just compiled it locally.

      CPack: Create package using NSIS
      CPack: Install projects
      CPack: - Install project: climatology_pi
      CPack: Create package
      CPack: - package: C:/Users/Rick/Documents/GitHub/climatology_pi/build/climatology_pi-1.4.2-ov50-win32.exe generated.

by downloading the packages that appveyor.yml  uses in these lines:

    Line 40   - ps: Start-FileDownload https://downloads.sourceforge.net/project/opencpnplugins/opencpn_lib/4.99.1405-vc141_xp/opencpn.lib
    Line 41   - ps: Start-FileDownload http://opencpn.navnux.org/build_deps/OpenCPN_buildwin-4.99a.7z

Then put opencpn.lib in a newly created "build" directory  and extract with 7z the Opencpn_buildwin-4.99a.7z  into buildwin directory.

Since you already have wxWidgets configured, etc. now all you need to do is build it.

Best
Rick
