### ISSUE TITLE
ov50 - Climatology makes Wx_routing fail and crashes ov50

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/climatology_pi#49]
After merging this [PR #46](https://github.com/seandepagnier/climatology_pi/pull/46) for ov4.99mui or ov50 https://github.com/seandepagnier/climatology_pi/pull/46   or using this appveyor compiled version https://ci.appveyor.com/project/seandepagnier/climatology-pi/builds/22481701/artifacts

When Climatology is enabled with Weather_routing_pi and when Climatology Data is set to be used by Weather_routing when the grib file does not cover the time and area, Weather_routing and  Opencpn 4.99.1408 fails and crashes.

**Comment by did-g** [comment]
Hi,
I don't have a windows box and I can't reproduce it when running O with wine, (Windows compatibility layer for Linux), but it doesn't work either.

From testing, I think it as nothing to do with ov5 but wx 3.1... ie compiling 4.8.8 with 3.1 is broken too.
Looks like there's some of dkind of deadlock in UI code.

**Comment by rgleason** [comment]
did-g, I am sure I did not adequately describe the problem in Windows10.
1. Climatology for ov50 complies, can be installed and enabled.
2. Climatology for ov50 when enabled and clicked on at the Icon pops up a menu which hides immediately. Minimize O and you can grab the menu and pull it to the front. However I can't get climatology to display its normal wind indications using opengl on or off. Also when I click on almost anything in the preferences window OpenCPN crashes.

3. I am wondering if appveyer.yml or one of the other files I touched is missing something important?

**Comment by did-g** [comment]
@rgleason ,
I don't think so, moving to wx 3.1 has triggered some bugs on windows
Could you try the latest change?
https://ci.appveyor.com/api/buildjobs/v5y7055pal8ktjc1/artifacts/build%2Fclimatology_pi-1.4.1-ov50-win32.exe
Dialog box should stay on top and the click of death could be gone (I can't reproduce it with wine)

**Comment by rgleason** [comment]
Wx-Routing is working now. Thanks Didier. Closing.
