### ISSUE TITLE
ov50 - Wind Rose settings not saved. Need setting for the Font size to make numbers smaller.

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/climatology_pi#57]
Wind Rose setting are not saved and we need new FONT SIZE setting or relative font size setting for the numbers in the Wind Rose.

These are the settings that work best for me. The relative font size is not right.  Also the settings are completely lost whenever I close the plugin. 

![screenshot 75](https://user-images.githubusercontent.com/2363959/53378433-89d40680-3933-11e9-88e1-31ff59f298ea.png)

**Comment by did-g** [comment]
Oops my mistake.

config file is already closed by O when climatology try to save settings.
+1 for a new font size setting.

**Comment by rgleason** [comment]
Closed, Didier #58 fixed.
