### ISSUE TITLE
Possible data problem  - When Data is NOT included, the Plugin deletes data on install

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/climatology_pi#6]
Possible data problem  - When Data is NOT included, the Plugin deletes data on install

When a user downloads a climatology.exe for windows and installs it. 
The plugin totally overwrites the climatology_pi/data directory also deleting all the data files!
This  problem should be fixed or the data should be included, because users are LOSING the data in their DATA directory!

Also
CMakeLists.txt    Line 17    SET(BUNDLE_DATA TRUE)
with  .../build/data/     (contains all the climate data)
and  .../buildwin/climatology_pi/data    (contains all the climate data)

There is NO data copied to the NSIS folders!
How does this work now?

**Comment by seandepagnier** [comment]
You can possibly modify the nsis installer file to not delete the data
folder somehow?

Otherwise, we just distribute installers which install the data which I
thought was the case anyway

**Comment by rgleason** [comment]
Sean was this fixed by just including the Data?  Or were changes made to the installer so it would not delete existing data when it installed over the top of an existing set of data?

Should this be closed or left open?

**Comment by dominig** [comment]
I have package the Climatogy (for OpenSUSE) and I do not see where are the data to be coopied on the target what leads the plugins to fail.
Please, could you point me at where are located the relevant data.
Thanks.

**Comment by rgleason** [comment]
Sorry this seems to be a re-occurant problem. The data is normally packaged. You will find the data on sourceforge opencpnplugins under the climatology folder called CDATA 1.0 or something similar it is about 5 to 7 mb

**Comment by dominig** [comment]
Rick,
    
    thanks. I have taken the file from SourceForges and added it in the
    OpenSUSE package.
    It would be nice for packager to indicate in the OpenCPN plugin page
    a link to the data near the link to the source code as well as
    adding the link in the README.
    
    Regards
    Dominig ar Foll
Senior Software Architect
Open Source Technology Centre
Intel SSG
    Le 10/06/2015 11:21, Rick Gleason a
      écrit :
    
    
      Sorry this seems to be a re-occurant problem. The data is
        normally packaged. You will find the data on sourceforge
        opencpnplugins under the climatology folder called CDATA 1.0 or
        something similar it is about 5 to 7 mb
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by rgleason** [comment]
http://sourceforge.net/projects/opencpnplugins/files/climatology_pi/
CL-Data-1.0.tar.xz
unpack it and put the data in plugins/climatology_pi/data/

**Comment by nohal** [comment]
Dominig...
On Linux, the data files should go to */usr/share/opencpn/plugins/climatology_pi/data/*
nohal@knut:~/tmp$ ls -la /usr/share/opencpn/plugins/climatology_pi/data/
total 43180
drwxr-xr-x 2 root root    4096 Jun  7 16:31 .
drwxr-xr-x 3 root root    4096 Jun  7 16:31 ..
-rw-r--r-- 1 root root  194400 Mar 21  2014 airtemperature
-rw-r--r-- 1 root root    1778 Sep 12  2014 ClimatologyInformation.html
-rw-r--r-- 1 root root  194400 Mar 21  2014 cloud
-rw-r--r-- 1 root root 1038966 Sep 26  2014 current01
-rw-r--r-- 1 root root 1038966 Sep 26  2014 current02
-rw-r--r-- 1 root root 1038966 Sep 26  2014 current03
-rw-r--r-- 1 root root 1038966 Sep 26  2014 current04
-rw-r--r-- 1 root root 1038966 Sep 26  2014 current05
-rw-r--r-- 1 root root 1038966 Sep 26  2014 current06
-rw-r--r-- 1 root root 1038966 Sep 26  2014 current07
-rw-r--r-- 1 root root 1038966 Sep 26  2014 current08
-rw-r--r-- 1 root root 1038966 Sep 26  2014 current09
-rw-r--r-- 1 root root 1038966 Sep 26  2014 current10
-rw-r--r-- 1 root root 1038966 Sep 26  2014 current11
-rw-r--r-- 1 root root 1038966 Sep 26  2014 current12
-rw-r--r-- 1 root root  426501 Mar 21  2014 cyclone-atl
-rw-r--r-- 1 root root  188931 Mar 21  2014 cyclone-epa
-rw-r--r-- 1 root root   67473 Mar 21  2014 cyclone-nio
-rw-r--r-- 1 root root  258412 Mar 21  2014 cyclone-she
-rw-r--r-- 1 root root  117088 Mar 21  2014 cyclone-spa
-rw-r--r-- 1 root root  409678 Mar 21  2014 cyclone-wpa
-rw-r--r-- 1 root root    3850 May 28  2014 elnino_years.txt
-rw-r--r-- 1 root root  777600 Mar 21  2014 lightning
-rw-r--r-- 1 root root  124416 Mar 21  2014 precipitation
-rw-r--r-- 1 root root     270 Mar 21  2014 README
-rw-r--r-- 1 root root  777600 Mar 21  2014 relativehumidity
-rw-r--r-- 1 root root   64800 Mar 21  2014 seadepth
-rw-r--r-- 1 root root  388800 Mar 21  2014 sealevelpressure
-rw-r--r-- 1 root root  185891 Sep 27  2014 sealevelpressure.gz
-rw-r--r-- 1 root root  777600 Mar 21  2014 seasurfacetemperature
-rw-r--r-- 1 root root  299999 Sep 27  2014 seasurfacetemperature.gz
-rw-r--r-- 1 root root 2230268 Sep 28  2014 wind01
-rw-r--r-- 1 root root 2255983 Sep 28  2014 wind02
-rw-r--r-- 1 root root 2262793 Sep 28  2014 wind03
-rw-r--r-- 1 root root 2243109 Sep 28  2014 wind04
-rw-r--r-- 1 root root 2223500 Sep 28  2014 wind05
-rw-r--r-- 1 root root 2162047 Sep 28  2014 wind06
-rw-r--r-- 1 root root 2142795 Sep 28  2014 wind07
-rw-r--r-- 1 root root 2172253 Sep 28  2014 wind08
-rw-r--r-- 1 root root 2197952 Sep 28  2014 wind09
-rw-r--r-- 1 root root 2167968 Sep 28  2014 wind10
-rw-r--r-- 1 root root 2157453 Sep 28  2014 wind11
-rw-r--r-- 1 root root 2187114 Sep 28  2014 wind12

**Comment by rgleason** [comment]
Thanks Pavel.  I figured out inclusion of data before compiling.. It basically had to go into a Project_Source_Dir/data  rather than under buildwin/data as before.

**Comment by dominig** [comment]
To be honest when creating Linux packages it's as simple to manage an external file (as long as I know where to get it from).
But if you end by including the data in the source tree, just let me know I will align my packaging.
But so far dor me that is not anymore an issue as the fix (using an external file) is nice and easy to use in my package.

**Comment by nohal** [comment]
No the data will not be included in the source tree and stay an external download.
It just has to be inside the tree if you want to create the monolythic package which includes them.
On DEB based distributions, I made them a separate package ```opencpn-plugin-climatology-data``` as they seem to change much less often than the code and are much bigger.

**Comment by rgleason** [comment]
Maybe that is what we should do with Windows?  Have two install packages?  Would that be easier for you?

**Comment by nohal** [comment]
No. It would just be more confusing for the users.
