### ISSUE TITLE
How to have CMAKE include DATA in compile

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/climatology_pi#7]
To include Data in the bundling
--------------------------------------------
Sorry I thought I had written about this DATA problem. Here is what I found works (I did it about 4 days ago, but I think this is about right).  Make these changes,

..o-plugin\climatology_pi\CMakeList.txt   Line 17
SET(BUNDLE_DATA TRUE)     <---change to TRUE, it was false

..o-plugin\climatology_pi\cmake\PluginConfigure.cmake

IF (COMMAND cmake_policy)
  CMAKE_POLICY(SET CMP0003 OLD)
  CMAKE_POLICY(SET CMP0005 OLD)
  CMAKE_POLICY(SET CMP0011 OLD)
  CMAKE_POLICY(SET CMP0012 NEW)  <--- added this line
ENDIF (COMMAND cmake_policy)

Then with all the current 'data' here
..\o-plugin\climatology_pi\data

After running cmake  the Data should be copied here
..\o-plugin\climatology_pi\build\_CPack_Packages\win32\NSIS\climatology_pi-1.0-win32\plugins\climatology_pi\data

After running cpack (for windows NSIS installer)
the exe file should be about 5-6 mb and include the data.

**Comment by seandepagnier** [comment]
Great,

This one slipped under me in a pull request and I did not realize it
disabled including the data in the package.   I always want the data, so
every plugin is a single file to download.

Then on another boat here someone couldn't figure out how to get the data,
and it took me 30 minutes to figure out how to extract a tar.xz file in
windows (7 zip doesn't seem to complain when it doesn't have permission
just silently fails)

Sean

**Comment by nohal** [comment]
Sean...
Is there any reason to have the 3 files in https://github.com/seandepagnier/climatology_pi/tree/master/data when extracting the data archive containing the same is needed to create the complete package anyway? It makes creating the Linux packages a bit more complicated as there can't be duplicates and they have to be deleted during packaging...

**Comment by seandepagnier** [comment]
what is the purpose of this line:

CMAKE_POLICY(SET CMP0012 NEW) <--- added this line

**Comment by seandepagnier** [comment]
The 3 files were included because.. they were small and not binary. Not really good logical reasoning, so I will remove them.  I think the html file should go in a different directory eventually, possibly /doc as I would like to have revision control on it, but it would need to be installed.

Should I remove the data folder as well?

**Comment by seandepagnier** [comment]
Actually... would be possible to include the html file in git, but remove it from CL-DATA-1.0.tar.xz ?

**Comment by nohal** [comment]
Whatever. Just no conflicts as otherwise I must delete the files during the packaging process, needing hacks in the script, which otherwise can be universal for all the plugins.

**Comment by seandepagnier** [comment]
I removed the files from github.

**Comment by nohal** [comment]
Many thanks

**Comment by rgleason** [comment]
Included cmake policy et CMP0012 because an error came up and it would not compil.  Someyhing about reading true 
.  So I got it working.
What 3 files in data  and why do they need deletion?  Just to understand.

**Comment by seandepagnier** [comment]
what error exactly?

the files were duplicated in the data.tar.xz and in github and should only
exist in one place

**Comment by rgleason** [comment]
I can run that in the morning. It was something about how "true" cant be interpreted ... i' give you the exact message. It would not compile. I tried "1" in place of true i think, that did not help either.

**Comment by rgleason** [comment]
Commented out this line that I added in cmake/pluginConfigure.cmake  
# CMAKE_POLICY(SET CMP0012 NEW)

Run cmake ..

C:\Data-Dart\Up-Soft\Navigation\o-plugin\climatology_pi\build>cmake ..
-- *** Staging to build climatology_pi ***
-- Found OpenGL...
--     Lib: glu32opengl32
--     Include:
-- Install Prefix: C:/Program Files (x86)/climatology_pi
CMake Warning (dev) at cmake/PluginInstall.cmake:78 (IF):
  given arguments:

    "TRUE" "AND" "EXISTS" "C:/Data-Dart/Up-Soft/Navigation/o-plugin/climatology_
pi/data"

  An argument named "TRUE" appears in a conditional statement.  Policy
  CMP0012 is not set: if() recognizes numbers and boolean constants.  Run
  "cmake --help-policy CMP0012" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
Call Stack (most recent call first):
  CMakeLists.txt:71 (INCLUDE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: C:/Data-Dart/Up-Soft/Navigation/o-plugin/climatology_pi/build

It took awhile to get this working so I hope the next version still builds with data!!!
(I had to duplicate this comment because it was not uploaded for some reason.)

**Comment by lanceberc** [comment]
On OSX:

cd climatology_pi
tar xzf ~/Downloads/CL-DATA-1.0.tar.xz 
mkdir build
cd build
cmake ..
make
make create-pkg
open Climatology-Plugin_1.0.pkg

Worked flawlessly.

**Comment by rgleason** [comment]
Will add to the readme if it is not there.
