### ISSUE TITLE
crash or hang when switching from a 31 day month to a 30 day month on the 31st.

### ISSUE THREAD

**Issue by LeaseOnLife** [seandepagnier/climatology_pi#76]
I can reproduce it this way: select a month with 31 days, select the 31st. then select a month that has less days than 31 => crash

**Comment by seandepagnier** [comment]
https://github.com/seandepagnier/climatology_pi/commit/15d410124286d3c9718ec865662b5fddf141da9e

**Comment by rgleason** [comment]
No, this has not been done, note that Bdbcat made changes before that here
https://github.com/rgleason/climatology_pi/commit/6c4980fa84bd2eb140d5dee0c04681f1309ca854
